import type { PlayerState, Debt } from '@/core/types';
import { createEmptyQuarterlyReport } from '@/core/lib/calculations/financial-helpers';

export const createMockPlayer = (overrides?: Partial<PlayerState>): PlayerState => ({
  id: 'test',
  name: 'Test Player',
  archetype: 'worker',
  countryId: 'russia',
  age: 25,
  cash: 50000,
  assets: [],
  debts: [],
  personal: {
    health: 100,
    happiness: 100,
    energy: 100,
    sanity: 100,
    intelligence: 100,
    relations: { family: 50, friends: 50, colleagues: 50 },
    skills: [],
    activeCourses: [],
    activeUniversity: [],
    buffs: [],
    lifeGoals: [],
    isDating: false,
    potentialPartner: null,
    pregnancy: null,
    familyMembers: [],
  },
  quarterlyReport: createEmptyQuarterlyReport(),
  quarterlySalary: 150000,
  happinessMultiplier: 1,
  health: 100,
  energy: 100,
  jobs: [],
  activeFreelanceGigs: [],
  businesses: [],
  ...overrides,
});